#!/usr/bin/env python3
"""Sinh sprite sheet pixel-art gốc cho MyZoo (client/assets/sprites.png + sprites.json).

Mỗi sprite là lưới ký tự 16x16 (nhân vật 16x24), 1 ký tự = 1 pixel theo PALETTE.
Chạy: python3 tools/gen_sprites.py
"""
import json
import os
from PIL import Image

PALETTE = {
    ".": None,
    "K": (58, 42, 30),      # viền / mắt
    "W": (255, 255, 255),
    "C": (255, 243, 214),   # kem
    "F": (255, 220, 176),   # da
    "p": (240, 168, 184),   # hồng
    "r": (217, 83, 79),     # đỏ
    "R": (224, 123, 57),    # cam
    "Y": (247, 211, 84),    # vàng
    "O": (232, 163, 61),    # vàng đậm
    "G": (106, 190, 48),    # lá sáng
    "g": (74, 143, 41),     # lá đậm
    "E": (46, 107, 30),     # lá tối
    "B": (93, 173, 226),    # xanh dương
    "b": (46, 109, 164),    # xanh đậm
    "P": (155, 89, 182),    # tím
    "N": (122, 82, 48),     # nâu
    "n": (176, 128, 80),    # nâu sáng
    "S": (138, 90, 59),     # đất
    "s": (110, 66, 39),     # đất tối
    "t": (169, 124, 80),    # đất sáng
    "A": (184, 184, 192),   # xám sáng
    "a": (138, 138, 149),   # xám
    "L": (144, 108, 63),    # rơm
    "D": (198, 226, 255),   # băng/kim cương sáng
}

S = {}

S["tile_grass"] = """
GGGGGGGGGGGGGGGG
GGGgGGGGGGGgGGGG
GGGGGGGgGGGGGGGG
GgGGGGGGGGGGGGgG
GGGGGGGGGGgGGGGG
GGGGgGGGGGGGGGGG
GGGGGGGGGGGGGgGG
GGgGGGGGgGGGGGGG
GGGGGGGGGGGGGGGG
GGGGGgGGGGGgGGGG
GgGGGGGGGGGGGGGG
GGGGGGGGgGGGGGGG
GGGGGGGGGGGGGgGG
GGgGGGgGGGGGGGGG
GGGGGGGGGGgGGGGG
GGGGGGGGGGGGGGGG
"""

S["tile_soil"] = """
ssssssssssssssss
sSSSSSSSSSSSSSSs
sSStSSSSSSSStSSs
sSSSSSSsSSSSSSSs
sSSSSSSSSSSSSSSs
sSsSSSSSSSStSSSs
sSSSSStSSSSSSSSs
sSSSSSSSSSsSSSSs
sSStSSSSSSSSSSSs
sSSSSSSSStSSSSSs
sSSSSsSSSSSSSsSs
sSSSSSSSSSSSSSSs
sStSSSSStSSSSSSs
sSSSSsSSSSSSStSs
sSSSSSSSSSSSSSSs
ssssssssssssssss
"""

S["tile_fence"] = """
................
................
.NN..........NN.
.NnN........NnN.
.NnNNNNNNNNNNnN.
.NnnnnnnnnnnnnN.
.NnNNNNNNNNNNnN.
.NnN........NnN.
.NnN........NnN.
.NnNNNNNNNNNNnN.
.NnnnnnnnnnnnnN.
.NnNNNNNNNNNNnN.
.NnN........NnN.
.NN..........NN.
................
................
"""

S["sprout"] = """
................
................
................
................
................
......G.........
.....GgG........
......g.G.......
......g.gG......
.....GgGg.......
......gg........
......g.........
................
................
................
................
"""

S["plant_mid"] = """
................
................
................
.....G..G.......
....GgGGgG......
...GgggggG......
....GgGgG.......
..G..gg..G......
.GgG.gg.GgG.....
..gg.gg.gg......
...ggggggg......
.....ggg........
......g.........
................
................
................
"""

# --- cây READY: icon riêng từng loại ---
S["crop_wheat"] = """
................
....Y..Y..Y.....
...YOY.YOYOY....
...YOYYOYYOY....
....YOYOYOY.....
...YOYYOYYOY....
....YOYOYOY.....
...YOYYOYYOY....
....YYYYYYY.....
.....g.g.g......
.....g.g.g......
......ggg.......
......gg........
.......g........
................
................
"""

S["crop_corn"] = """
................
......GG........
.....GggG.......
......YY........
.....YOYY.......
.....YYOY.......
.G...YOYY...G...
.gG..YYOY..Gg...
..gG.YOYY.Gg....
...ggYYOYgg.....
.....YOYY.......
.....gYYg.......
......gg........
......g.........
................
................
"""

S["crop_carrot"] = """
................
.....G..G.......
....GgGgG.......
.....GgG........
......g.........
.....RRR........
....RRRRR.......
....RRRRR.......
....RRRRR.......
.....RRR........
.....RRR........
......RR........
......R.........
................
................
................
"""

S["crop_lettuce"] = """
................
................
................
....GGGG........
..GGgGGgGG......
.GGgGGGGgGG.....
.GgGGgGGGgG.....
.GGGgGGgGGG.....
.GgGGGGGgGG.....
..GgGgGgGG......
...GGGGGG.......
................
................
................
................
................
"""

S["crop_potato"] = """
................
................
................
................
....nnnn........
...nnNnnn.......
..nnnnnNnn......
..nNnnnnnn......
..nnnnNnnn......
...nnnnnn.......
....nnnn........
................
................
................
................
................
"""

S["crop_grass"] = """
................
................
................
..G...G...G.....
..g.G.g.G.g.....
..g.g.g.g.g.....
.Gg.gGg.gGg.....
.gg.ggg.ggg.....
.ggGgggGggg.....
..ggggggggg.....
...ggggggg......
................
................
................
................
................
"""

S["crop_bamboo"] = """
................
....g...G.......
...GgG..g.......
....g..GgG......
....gg..g.......
....gE..gg......
....g...gE......
...GgG..g.......
....g...g.......
....gE.GgG......
....g...gE......
....gg..g.......
....g...g.......
....g...g.......
................
................
"""

S["crop_berry"] = """
................
.....G.G........
....GgGgG.......
.....GgG........
....r.g.r.......
...rrr.rrr......
...rrW.rrW......
...rrr.rrr......
....r.r.r.......
.....rrr........
.....rrW........
.....rrr........
......r.........
................
................
................
"""

# --- thú chibi 16x16 ---
S["animal_rabbit"] = """
...KK....KK.....
..KWWK..KWWK....
..KWpK..KpWK....
..KWpK..KpWK....
..KWWK..KWWK....
...KWWKKWWK.....
..KWWWWWWWWK....
.KWWWWWWWWWWK...
.KWKWWWWWWKWK...
.KWWWWppWWWWK...
.KWWWpWWpWWWK...
..KWWWWWWWWK....
..KWWWWWWWWK....
.KWWWKWWKWWWK...
.KWWWWWWWWWWK...
..KKKKKKKKKK....
"""

S["animal_sheep"] = """
................
....KKKKKK......
...KWWWWWWK.....
..KWWWWWWWWK....
.KWWWWWWWWWWK...
.KWWKFFFFKWWK...
.KWWFKFFKFWWK...
.KWWFFFFFFWWK...
.KWWFFppFFWWK...
.KWWWFFFFWWWK...
.KWWWWWWWWWWK...
..KWWWWWWWWK....
..KWWWWWWWWK....
...KFKFFKFK.....
...KFKFFKFK.....
....KK..KK......
"""

S["animal_monkey"] = """
................
...KNNNNNNK.....
..KNNNNNNNNK....
.KNKFFFFFFKNK...
.KNFFFFFFFFNK...
.KNFKFFFFKFNK...
..KFFFFFFFFK....
..KFFpFFpFFK....
..KFFFKKFFFK....
...KFFFFFFK.....
..KNNNNNNNNK....
.KNNFFFFFFNNK...
.KNNFFFFFFNNK.K.
..KNNNNNNNNK.KN.
..KNK.KNK.KNKN..
..KK...KK..KK...
"""

S["animal_giraffe"] = """
....K.K.........
...KYKYK........
...KYYYK........
..KYYYYYK.......
..KYKYKYK.......
..KYYYYYK.......
...KYYYK........
...KYNYK........
...KYYK.........
...KYNYK........
...KYYK..KKK....
...KYNYKKYYYK...
..KYYYYYYYNYK...
..KYYNYYYYYYK...
..KYYYYNYYYK....
...KKKKKKKK.....
"""

S["animal_elephant"] = """
................
....KKKKKKKK....
.KKKAAAAAAAAKKK.
KAAKAAAAAAAAKAAK
KAaAKAAAAAAKAaAK
KAaAKKAAAAKKAaAK
KAAKAKAAAAKAKAAK
.KKKAApAApAAKKK.
...KAAAAAAAAK...
...KAAKAAKAAK...
....KKKAAKKK....
......KAAK......
......KAAK......
......KAAK......
......KAApK.....
.......KKK......
"""

S["animal_panda"] = """
...KKK....KKK...
..KKKKK..KKKKK..
..KKKKKKKKKKKK..
.KWWWWWWWWWWWWK.
.KWWKKWWWWKKWWK.
.KWKKKKWWKKKKWK.
.KWKKWKWWKWKKWK.
.KWWKKWWWWKKWWK.
.KWWWWKKKKWWWWK.
..KWWWWWWWWWWK..
..KKKWWWWWWKKK..
.KKKKWWWWWWKKKK.
.KKKKWWWWWWKKKK.
..KKWWWWWWWWKK..
...KKKWWWWKKK...
.....KKKKKK.....
"""

# --- trái cây minigame ---
S["fruit_apple"] = """
................
.......K........
......Kg........
.....Kg.........
....rrKrr.......
...rrrrrrr......
..rrrrrrrrr.....
..rrWrrrrrr.....
..rrWrrrrrr.....
..rrrrrrrrr.....
...rrrrrrr......
....rrrrr.......
................
................
................
................
"""

S["fruit_grape"] = """
................
......Kg........
.....Kg.........
....P.P.P.......
...PPPPPPP......
...PWPPPPP......
....PPPPP.......
...PPPPPPP......
...PPPPPPP......
....PPPPP.......
.....PPP........
.....PPP........
......P.........
................
................
................
"""

S["fruit_orange"] = """
................
.......Kg.......
......KgG.......
....RRRRR.......
...RRRRRRR......
..RRRRRRRRR.....
..RRWRRRRRR.....
..RRWRRRRRR.....
..RRRRRRRRR.....
...RRRRRRR......
....RRRRR.......
................
................
................
................
................
"""

S["fruit_lemon"] = """
................
................
.......KY.......
.....YYYY.......
....YYYYYY......
...YYYYYYYY.....
..YYWYYYYYYY....
..YYWYYYYYYY....
...YYYYYYYY.....
....YYYYYY......
.....YYYY.......
......YY........
................
................
................
................
"""

S["fruit_blueberry"] = """
................
................
......Kg........
.....K..........
....BBBBB.......
...BBBBBBB......
..BBbBBBBBB.....
..BBWBBBBBB.....
..BBWBBBBBB.....
..BBBBBBBbB.....
...BBBBBBB......
....BBBBB.......
................
................
................
................
"""

# --- icon ---
S["icon_coin"] = """
................
.....KKKK.......
...KKOYYOKK.....
..KOYYYYYYOK....
..KOYWYYYYOK....
.KOYWYYYYYYOK...
.KOYYYYOYYYOK...
.KOYYYOYYYYOK...
.KOYYOYYYYYOK...
..KOYYYYYYOK....
..KOYYYYYYOK....
...KKOYYOKK.....
.....KKKK.......
................
................
................
"""

S["icon_gem"] = """
................
................
...KKKKKKKK.....
..KDBBBBBBDK....
..KBDBBBBDBK....
...KBDBBDBK.....
...KBBDDBBK.....
....KBBBBK......
....KBBBBK......
.....KBBK.......
.....KBBK.......
......KK........
................
................
................
................
"""

S["icon_heart"] = """
................
................
...pp....pp.....
..prrp..prrp....
.prrrrpprrrrp...
.prrWrrrrrrrp...
.prrWrrrrrrrp...
.prrrrrrrrrp....
..prrrrrrrp.....
...prrrrrp......
....prrrp.......
.....prp........
......p.........
................
................
................
"""

S["icon_hungry"] = """
................
......rr........
.....rrrr.......
.....rrrr.......
.....rrrr.......
......rr........
......rr........
......rr........
......rr........
................
......rr........
.....rrrr.......
......rr........
................
................
................
"""

# --- nhân vật 16x24 ---
S["char_farmer"] = """
......LLLL......
....LLLLLLLL....
...LLLLLLLLLL...
..LLLLLLLLLLLL..
.LLLLLLLLLLLLLL.
..KFFFFFFFFFFK..
..KFFFFFFFFFFK..
..KFKFFFFFFKFK..
..KFFFFFFFFFFK..
..KFFKFFFFKFFK..
..KFFFKKKKFFFK..
...KFFFFFFFFK...
....KFFFFFFK....
....KGGGGGGK....
...KGGGGGGGGK...
..KFGGGGGGGGFK..
..KFGGGGGGGGFK..
...KGGGGGGGGK...
....KGGGGGGK....
....KNNKKNNK....
....KNNKKNNK....
....KNNKKNNK....
...KNNNKKNNNK...
....KKK..KKK....
"""

S["char_keeper"] = """
......BBBB......
....BBBBBBBB....
...BBBBBBBBBB...
..BBBBBbbbbbbb..
..KFFFFFFFFFFK..
..KFFFFFFFFFFK..
..KFKFFFFFFKFK..
..KFFFFFFFFFFK..
..KFFKFFFFKFFK..
..KFFFKKKKFFFK..
...KFFFFFFFFK...
....KFFFFFFK....
....KBBBBBBK....
...KBBBBBBBBK...
..KFBBBBBBBBFK..
..KFBBBBBBBBFK..
...KBBBBBBBBK...
....KBBBBBBK....
....KbbKKbbK....
....KbbKKbbK....
....KbbKKbbK....
...KbbbKKbbbK...
....KKK..KKK....
"""


def parse(text):
    rows = [r for r in text.strip("\n").split("\n")]
    w = max(len(r) for r in rows)
    return [r.ljust(w, ".") for r in rows], w, len(rows)


def main():
    parsed = {}
    for name, text in S.items():
        rows, w, h = parse(text)
        for r in rows:
            for ch in r:
                if ch not in PALETTE:
                    raise SystemExit(f"{name}: ký tự lạ '{ch}'")
        parsed[name] = (rows, w, h)

    pad = 1
    cols = 8
    cell_w = max(v[1] for v in parsed.values()) + pad
    cell_h = max(v[2] for v in parsed.values()) + pad
    names = sorted(parsed)
    rows_count = (len(names) + cols - 1) // cols
    sheet = Image.new("RGBA", (cols * cell_w, rows_count * cell_h), (0, 0, 0, 0))
    atlas = {}
    for i, name in enumerate(names):
        grid, w, h = parsed[name]
        ox, oy = (i % cols) * cell_w, (i // cols) * cell_h
        for y, row in enumerate(grid):
            for x, ch in enumerate(row):
                color = PALETTE[ch]
                if color:
                    sheet.putpixel((ox + x, oy + y), (*color, 255))
        atlas[name] = {"x": ox, "y": oy, "w": w, "h": h}

    out_dir = os.path.join(os.path.dirname(__file__), "..", "client", "assets")
    os.makedirs(out_dir, exist_ok=True)
    sheet.save(os.path.join(out_dir, "sprites.png"))
    with open(os.path.join(out_dir, "sprites.json"), "w") as f:
        json.dump(atlas, f, indent=1)
    print(f"OK: {len(names)} sprites -> client/assets/sprites.png ({sheet.width}x{sheet.height})")


if __name__ == "__main__":
    main()
